# ==============================================================
# SECRETS — FIXED
#
# BUG FIXED: DATABASE_URL hostnames were wrong.
# Old (broken): postgres-auth, postgres-product, postgres-order
# Fixed:        auth-db, product-db, order-db
# These MUST match the Kubernetes Service names exactly.
# ==============================================================

# ── Auth Service ──────────────────────────────────────────────
########kkkkkkk
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: ecommerce
type: Opaque
data:
  # postgresql+asyncpg://auth_user:auth_pass@auth-db:5432/auth_db
  DATABASE_URL: cG9zdGdyZXNxbCthc3luY3BnOi8vYXV0aF91c2VyOmF1dGhfcGFzc0BhdXRoLWRiOjU0MzIvYXV0aF9kYg==
  JWT_SECRET_KEY: c3VwZXJzZWNyZXRqd3RrZXlfY2hhbmdlX2luX3Byb2R1Y3Rpb25fcGxlYXNl
---
# ── Product Service ───────────────────────────────────────────
apiVersion: v1
kind: Secret
metadata:
  name: product-service-secret
  namespace: ecommerce
type: Opaque
data:
  # postgresql+asyncpg://product_user:product_pass@product-db:5432/product_db
  DATABASE_URL: cG9zdGdyZXNxbCthc3luY3BnOi8vcHJvZHVjdF91c2VyOnByb2R1Y3RfcGFzc0Bwcm9kdWN0LWRiOjU0MzIvcHJvZHVjdF9kYg==
  JWT_SECRET_KEY: c3VwZXJzZWNyZXRqd3RrZXlfY2hhbmdlX2luX3Byb2R1Y3Rpb25fcGxlYXNl
---
# ── Order Service ─────────────────────────────────────────────
apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
  namespace: ecommerce
type: Opaque
data:
  # postgresql+asyncpg://order_user:order_pass@order-db:5432/order_db
  DATABASE_URL: cG9zdGdyZXNxbCthc3luY3BnOi8vb3JkZXJfdXNlcjpvcmRlcl9wYXNzQG9yZGVyLWRiOjU0MzIvb3JkZXJfZGI=
  JWT_SECRET_KEY: c3VwZXJzZWNyZXRqd3RrZXlfY2hhbmdlX2luX3Byb2R1Y3Rpb25fcGxlYXNl
---
# ── Auth DB ───────────────────────────────────────────────────
apiVersion: v1
kind: Secret
metadata:
  name: auth-db-secret
  namespace: ecommerce
type: Opaque
data:
  POSTGRES_DB: YXV0aF9kYg==
  POSTGRES_USER: YXV0aF91c2Vy
  POSTGRES_PASSWORD: YXV0aF9wYXNz
---
# ── Product DB ────────────────────────────────────────────────
apiVersion: v1
kind: Secret
metadata:
  name: product-db-secret
  namespace: ecommerce
type: Opaque
data:
  POSTGRES_DB: cHJvZHVjdF9kYg==
  POSTGRES_USER: cHJvZHVjdF91c2Vy
  POSTGRES_PASSWORD: cHJvZHVjdF9wYXNz
---
# ── Order DB ──────────────────────────────────────────────────
apiVersion: v1
kind: Secret
metadata:
  name: order-db-secret
  namespace: ecommerce
type: Opaque
data:
  POSTGRES_DB: b3JkZXJfZGI=
  POSTGRES_USER: b3JkZXJfdXNlcg==
  POSTGRES_PASSWORD: b3JkZXJfcGFzcw==
---
# ── RabbitMQ ──────────────────────────────────────────────────
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: ecommerce
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: Z3Vlc3Q=
  RABBITMQ_DEFAULT_PASS: Z3Vlc3Q=
